### ISSUE TITLE
For consistency, should "strategies" be "all_strategies"

### ISSUE THREAD

**Issue by mojones** [Axelrod-Python/tournament#27]
Just a tiny point but this trips me up every time; the files named _strategies.*_ in the tournament correspond to the list of classes in _axelrod.ordinary_strategies_, and the files named _all_strategies_ correspond to the list of classes in _axelrod.strategies_. So in the tournament, _strategies_ includes the cheating ones, but in the library, it doesn't. This causes me to look at the wrong box plot every. single. time. :-) and I fear it's too late to retrain myself. Should we have consistent:
- all_strategies
- ordinary_strategies
- basic_strategies
- cheating_strategies

and keep the word **strategies** for generic chat?

**Comment by drvinceknight** [comment]
I definitely think that `axelrod.strategies` should stay as all the strategies in the library. In line with a move to less classification of the strategies in the library itself I think this needs to stay: it lets users quickly have access to all the strategies.

**But** I'm not adverse to relabelling the output file names to be consistent.

That would be a pretty simple thing to do: just changing a default. So:
- `strategies_boxplot.svg` :arrow_right: `strategies_nocheaters_boxplot.svg`
- `cheating_strategies_boxplot.svg` no change :sleeping: 
- `basic_strategies_boxplot.svg`: no change :sleeping: 
- `all_strategies_boxplot.svg` :arrow_right: `strategies_boxplot.svg`

How does that sound?

**Comment by mojones** [comment]
I prefer 

strategies_boxplot.svg ￼ -> ordinary_strategies_boxplot.svg

for consistency with the library.

**Comment by drvinceknight** [comment]
> I prefer
> 
> strategies_boxplot.svg ￼ -> ordinary_strategies_boxplot.svg
> 
> for consistency with the library.

Yes me too. Much better suggestion than mine. So:
- strategies_boxplot.svg :arrow_right: ordinary_strategies_boxplot.svg
- cheating_strategies_boxplot.svg no change :sleeping:
- basic_strategies_boxplot.svg: no change :sleeping:
- all_strategies_boxplot.svg :arrow_right: strategies_boxplot.svg

**Comment by marcharper** [comment]
I'm in favor, just note that we'll need to change documentation links and such as well, so be on the look out for broken links.

**Comment by drvinceknight** [comment]
I've submitted a PR to the library that changes `run_axelrod` and all the tournament managers there: https://github.com/Axelrod-Python/Axelrod/pull/514.

Going to put a PR together here that changes this here and also addresses #26 (which is in the PR over there).

**Comment by drvinceknight** [comment]
Ran in to #31.

**Comment by drvinceknight** [comment]
This has been addressed. See: http://axelrod-tournament.readthedocs.org/en/latest/index.html
