### ISSUE TITLE
Unexpected behaviour for cheating strategies?

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/tournament#28]
I don't understand why the mind benders etc haven't simply overridden the other strategies to be cooperators? Is this something to do with the cloning?

https://github.com/Axelrod-Python/tournament/blob/gh-pages/assets/all_strategies_boxplot.svg

(Weirdly Meta Minority and $e$ are at the top of that? :confused: )

**Comment by marcharper** [comment]
Perhaps the way we are resetting the players now is different? Maybe the order of play matters?

**Comment by drvinceknight** [comment]
Yeah, perhaps...
