### ISSUE TITLE
Add link to read docs.

### ISSUE THREAD

**Issue by Nikoleta-v3** [Axelrod-Python/tournament#39]
Could we add the link for the website (http://axelrod-tournament.readthedocs.io/en/latest/#) on the description please.

**Comment by drvinceknight** [comment]
Sure, open a PR :)

**Comment by Nikoleta-v3** [comment]
*Question*: Can I open a PR for the description of the repository?

**Comment by drvinceknight** [comment]
Ah sorry! I misunderstood. Adding the url now.

**Comment by drvinceknight** [comment]
Done.
