### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by samching** [Axelrod-Python/tournament#42]
When running `python run_noisy.py' (after cloning the repo), I run into the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/strategies_noisy_interactions.csv'
```
I believe this is due to the fact that the `data\` folder is missing. Only after creating the `data\` folder, the error is no longer thrown. Perhaps you could update the README.md to get first time users to create the folder before running?

Thanks.

**Comment by drvinceknight** [comment]
Good idea, thanks I'll do that.

**Comment by drvinceknight** [comment]
Let me know what you think @samuelcwl: https://github.com/Axelrod-Python/tournament/pull/43

**Comment by samching** [comment]
Looks good to me! Thanks for adding it in.
